name: backend build
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - develop
  push:
    branches:
      - main

permissions: write-all

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-build:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        id: setup_node

      - name: Restore node modules or npm install
        uses: ./.github/actions/cache-or-install
        with:
          working-directory: backend
          node-version: ${{ steps.setup_node.outputs.node-version }}

      - name: echo
        run: ls -la

      - name: Build
        run: npm run build
