name: Save node_modules for cache
on:
  push:
    branches:
      - main
    paths:
      - "backend/package-lock.json"
      - "web/package-lock.json"
      - ".github/workflows/cache-modules.yml"

permissions: write-all

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      working-directories: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'backend/package-lock.json'
            web:
              - 'web/package-lock.json'

  save-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: paths-filter
    strategy:
      matrix:
        runner: [ubuntu-latest, debian-latest]
        working-directory: ${{ fromJSON(needs.paths-filter.outputs.working-directories) }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        id: setup_node

      - name: Save node modules
        uses: ./.github/actions/cache-or-install
        with:
          working-directory: ${{ matrix.working-directory }}
          node-version: ${{ steps.setup_node.outputs.node-version }}
